### ISSUE TITLE
Repository transfer proposal

### ISSUE THREAD

**Issue by alerque** [w3c/font-text-cg-temp#1]
*Before* this repo goes any farther, can I propose that we ⓐ rename & archive or delete this repo out of the way, then ⓑ transfer [this repo](https://github.com/font-text/font-text.github.io) into this org namespace, then ⓒ rename it as appropriate, then ⓓ cherry pick the commits to this repo to the other one to bring it up to speed with the code of conduct, etc. This will best preserve the edit and comment history to the charter which I believe is significant.

**Comment by lianghai** [comment]
Right. I suggested (a), (c), and (b) to @svgeesus yesterday, but didn’t realized the possibility of (d). Let’s wait for Chris’s response.

**Comment by alerque** [comment]
Operation ⓓ is a bit of advanced Git foo whereby you can `git cherry-pick` or even `git merge` from repositories that don't have the same root. I'd be happy to take care of that step. In fact let me just open a PR onto the original repository with that step done so that it will come across ready made with the transfer in ⓑ.

**Comment by xfq** [comment]
This suggestion looks good to me, so I'll go ahead and do it today.

@svgeesus If you think there is anything wrong, please let me know.

**Comment by xfq** [comment]
- [x] rename this repo
- [x] transfer the CG repo into w3c org namespace
- [x] make sure that people who have owner/admin permissions in the old CG repo have owner/admin permissions in the new CG repo too
- [x] rename it as appropriate
- [x] cherry pick the commits to the new repo
- [ ] archive/delete the old repo (this repo)

I will modify the task list here after I finish each step.

**Comment by alerque** [comment]
Thanks @xfq. I've done the cherry-picking (see [this PR](https://github.com/w3c/font-text-cg/pull/2#event-3810297277)) and merged the result. Everything from this repo is already in the replacement, I think the only step left is to archive/delete.

**Comment by alerque** [comment]
(Closing this issue in case the decision is to archive, in which case this can't be closed later and it's nice to have zero open issues — but deletion is probably a fine outcome too.)
